---

driver:
  name: vagrant
  provider:
    name: vmware_desktop
lint:
  name: yamllint
platforms:
  - name: bar
    box: StefanScherer/windows_2016
provisioner:
  name: ansible
  connection_options:
    sudo: false
    ansible_user: vagrant
    ansible_password: vagrant
    ansible_port: 55985
    ansible_connection: winrm
    ansible_winrm_scheme: http
    ansible_winrm_server_cert_validation: ignore
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
